import type { TikTokAdAccount, TikTokCampaign } from "./types";

export const INITIAL_MOCK_AD_ACCOUNT: TikTokAdAccount = {
  id: "tt-acc-10928",
  advertiserId: "ADV-74920412891",
  advertiserName: "هەژماری ڕیکلامی براند",
  currency: "USD",
  timezone: "Asia/Baghdad (GMT+3)",
  status: "connected",
  lastSyncedAt: new Date(Date.now() - 1000 * 60 * 14).toISOString(), // 14 mins ago
  accountType: "AUCTION",
};

export const INITIAL_MOCK_CAMPAIGNS: TikTokCampaign[] = [
  {
    id: "camp-001",
    name: "کەمپەینی بەهار ٢٠٢٦ - ڕیکلامی تایبەت",
    objective: "TRAFFIC",
    status: "active",
    dailyBudget: 25.0,
    totalSpent: 165.4,
    impressions: 48920,
    clicks: 3410,
    ctr: 6.97,
    cpc: 0.048,
    conversions: 245,
    destinationPage: {
      id: "lt-1",
      title: "لاپەڕەی سەرەکی براند",
      slug: "main",
      type: "linktree",
    },
    targetAudience: {
      location: "هەولێر، سلێمانی، دهۆک",
      gender: "ALL",
      ageGroups: ["18-24", "25-34"],
      languages: ["Kurdish", "Arabic", "English"],
    },
    callToAction: "سەردانی وێبسایت بکە",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-06T14:30:00Z",
  },
  {
    id: "camp-002",
    name: "پڕۆمۆی بەرهەمی نوێ و داشکاندن",
    objective: "CONVERSIONS",
    status: "active",
    dailyBudget: 40.0,
    totalSpent: 280.0,
    impressions: 72150,
    clicks: 4620,
    ctr: 6.4,
    cpc: 0.06,
    conversions: 412,
    destinationPage: {
      id: "lt-2",
      title: "داشکاندنەکانی ئەم مانگە",
      slug: "offers",
      type: "linktree",
    },
    targetAudience: {
      location: "کوردستان و سەرجەم عێراق",
      gender: "ALL",
      ageGroups: ["18-24", "25-34", "35-44"],
      languages: ["Kurdish", "Arabic"],
    },
    callToAction: "ئێستا داوا بکە",
    createdAt: "2026-02-25T12:00:00Z",
    updatedAt: "2026-03-05T18:15:00Z",
  },
  {
    id: "camp-003",
    name: "ناساندنی خزمەتگوزارییەکان بۆ کۆمپانیاکان",
    objective: "LEAD_GENERATION",
    status: "paused",
    dailyBudget: 15.0,
    totalSpent: 94.2,
    impressions: 21400,
    clicks: 1120,
    ctr: 5.23,
    cpc: 0.084,
    conversions: 68,
    destinationPage: {
      id: "lt-3",
      title: "خزمەتگوزاری بازرگانی",
      slug: "b2b",
      type: "linktree",
    },
    targetAudience: {
      location: "هەولێر و بەغدا",
      gender: "ALL",
      ageGroups: ["25-34", "35-44", "45-54"],
      languages: ["Kurdish", "Arabic", "English"],
    },
    callToAction: "پەیوەندیمان پێوە بکە",
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-03-04T11:20:00Z",
  },
  {
    id: "camp-004",
    name: "ڕیکلامی ڤیدیۆیی - بینینی پەیج",
    objective: "COMMUNITY_INTERACTION",
    status: "review",
    dailyBudget: 20.0,
    totalSpent: 0.0,
    impressions: 0,
    clicks: 0,
    ctr: 0.0,
    cpc: 0.0,
    conversions: 0,
    destinationPage: {
      id: "lt-1",
      title: "لاپەڕەی سەرەکی براند",
      slug: "main",
      type: "linktree",
    },
    targetAudience: {
      location: "سەرجەم کوردستان",
      gender: "ALL",
      ageGroups: ["18-24", "25-34"],
      languages: ["Kurdish"],
    },
    callToAction: "سەردان بکە",
    createdAt: "2026-03-06T08:00:00Z",
    updatedAt: "2026-03-06T08:00:00Z",
  },
];

export const OBJECTIVE_LABELS: Record<string, { label: string; description: string }> = {
  TRAFFIC: {
    label: "ڕاکێشانی ترافیک (Traffic)",
    description: "ناردنی زیاتری بینەران بۆ لاپەڕەی لینکەکە یان وێبسایتەکەت",
  },
  CONVERSIONS: {
    label: "فرۆشتن و گۆڕین (Conversions)",
    description: "زیادکردنی کڕین و داواکاری لە ڕێگەی لاپەڕەکەتەوە",
  },
  LEAD_GENERATION: {
    label: "کۆکردنەوەی زانیاری (Lead Gen)",
    description: "کۆکردنەوەی پەیوەندی و ژمارەی کڕیارە شیاوەکان",
  },
  COMMUNITY_INTERACTION: {
    label: "کارلێکی بەکارهێنەران",
    description: "زیادکردنی فۆڵۆو و سەردانی پەیجی براندەکەت",
  },
};
